Cherry pick of 9fb7600ddb23f4d0f3cbbf7e6e46434869559dbe failed
stdout:

stderr:
14:38:15.737211 git.c:344               trace: built-in: git cherry-pick 9fb7600ddb23f4d0f3cbbf7e6e46434869559dbe
error: could not apply 9fb7600ddb2... [FIX] base, tools: properly distribute branding around removed elements
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: