[IMP] web: forward port missing variables and mixins from BS4 -> BS5
variable:
* $display4-weight
* $custom-control-gutter
* $table-cell-padding
* $table-cell-padding-sm
* $emphasized-link-hover-darken-percentage
* $link-decoration (not missing but to restore old behaviour)

mixins:
* hover
* hover-focus mixin
* plain-hover-focus
* text-emphasis-variant

Also, some Bootstrap 5, now use rem and Odoo px so calc don't work

we add forward port the BS4 variable `$modal-footer-margin-between`
to avoid error between px and rem calc.

e.g. of error:
Error: Incompatible units: 'rem' and 'px'.
padding: $modal-inner-padding - $modal-footer-margin-between * .5;