Cherry pick of cff53e078db2f3c9dc03a873f94146a7808e6989 failed
stdout:

stderr:
10:45:08.046217 git.c:344               trace: built-in: git cherry-pick cff53e078db2f3c9dc03a873f94146a7808e6989
error: could not apply cff53e078db... [IMP] test_mass_mailing: check partner_id usage in seen list
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: